### ISSUE TITLE
Passing own static property to @handle decorator fails.

### ISSUE THREAD

**Issue by davidjamesb** [alveflo/tsmediator#23] opened 2020-04-12 18:21 UTC
1. Created a new react app with `create-react-app my-app --template typescript`.
2. Installed **tsmediator** using `npm install --save tsmediator`.
3. Set `"experimentalDecorators": true` in **tsconfig.json**.
4. Use the supplied example in **README.md**:

```
@Handler(CmdHandler.Type)
class CmdHandler implements ICommandHandler<string, number> {
    public static get Type():string { return "foo"; }

    Log() {}

    Validate(payload: string) {
        if (payload !== 'foo bar') {
            throw Error('Some error');
        }
    }

    Handle(payload: string) {
        return 5 * 5;
    }
}    
```
5. Send through the mediator in **App.tsx**:
```
let mediator: Mediator = new Mediator();
mediator.Send(CmdHandler.Type, 5);
```

The following error is thrown:

`ReferenceError: Cannot access 'CmdHandler' before initialization`

The handler attribute cannot accept a static member from the class it is decorating. Using a static members from a different class works.

**Comment by alveflo** [comment] 2020-04-13 18:51
Hi @DJBMASTER , thanks for reportin this. However I'm not able to reproduce your issue.

This one is working for fine for me:
```typescript
@Handler(CmdHandler.Type)
class CmdHandler implements ICommandHandler<string, string> {
    public static get Type():string { return "foo"; }

    Log() {}

    Validate(payload: string) {
        if (payload !== 'foo bar') {
            throw Error('Some error');
        }
    }

    Handle(payload: string) {
        return `Hello ${payload}`;
    }
}    

class App extends React.Component<{}, undefined> {
    public render() {
        let mediator: Mediator = new Mediator();

        let result = mediator.Send(CmdHandler.Type, "foo bar");

        return (
            <div className="app">
                <h1>{ result }</h1>
            </div>
        );
    }
}

```

Does it even work for you to explicitly name the handler as `@Handler("foo")` and `mediator.Send("foo", "Something")`?

**Comment by alveflo** [comment] 2020-04-21 06:20
Closing this. Feel free to reopen if you've got any questions!

**Closed as completed by alveflo** 2020-04-21 06:20 UTC
